CHECKPOINT:
  eval_steps: 4000
  load_from_checkpoint: null
  log_path: models/saved_models/PASTIS24/logs_UNET3D
  partial_restore: false
  save_path: models/saved_models/MTLCC/UNET3D
  save_steps: 8000
  train_metrics_steps: 2000
DATASETS:
  eval:
    base_dir: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/total2
    batch_size: 32
    bidir_input: false
    dataset: PASTIS24_fold5
    extra_data: null
    max_seq_len: 21
    num_workers: 4
    paths: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/csv/val_90.csv
  train:
    base_dir: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/total2
    batch_size: 32
    bidir_input: false
    dataset: PASTIS24_fold5
    extra_data: null
    max_seq_len: 21
    num_workers: 4
    paths: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/csv/train_90.csv
MODEL:
  architecture: UNET3D
  dropout: 0.0
  img_res: 64
  max_seq_len: 21
  num_channels: 21
  num_classes: 4
  shape_pattern: NTHWC
SOLVER:
  class_weights: null
  loss_function: masked_cross_entropy
  lr_base: 0.0001
  lr_decay: 0.975
  lr_scheduler: null
  num_epochs: 300
  reset_lr: true
  reset_lr_at_epoch: 150
local_device_ids:
- 0
