CHECKPOINT:
  eval_steps: 2000
  load_from_checkpoint: null
  log_path: models/saved_models/PASTIS24_flod1/flod1_shijiankongjian_logs1
  partial_restore: false
  save_path: models/saved_models/PASTIS24_flod1/fold1_shijiankongjian
  save_steps: 20000000000
  train_metrics_steps: 250
DATASETS:
  eval:
    base_dir: G:/flod1
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 0
    paths: G:/flod1/csv/val.csv
  test:
    base_dir: G:/flod1
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 0
    paths: G:/flod1/csv/test.csv
  train:
    base_dir: G:/flod1
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 0
    paths: G:/flod1/csv/train.csv
MODEL:
  architecture: TSViT
  dim: 128
  dim_head: 32
  dropout: 0.2
  emb_dropout: 0.2
  heads: 4
  ignore_background: false
  img_res: 24
  max_seq_len: 60
  num_channels: 11
  num_classes: 19
  num_features: 16
  patch_size: 2
  pool: cls
  scale_dim: 4
  spatial_depth: 4
  temporal_depth: 4
SOLVER:
  class_weights: null
  loss_function: masked_cross_entropy
  lr_base: 1e-3
  lr_min: 5e-6
  lr_scheduler: cosine
  lr_start: 1e-8
  num_cycles: 1
  num_epochs: 100
  num_warmup_epochs: 10
  reset_lr: true
  steps: (0, 80000)
  weight_decay: 0.001
local_device_ids:
- 0
