CHECKPOINT:
  eval_steps: 4000
  load_from_checkpoint: null
  log_path: C:/Users/Think/Desktop/DeepSatModels-main/models/saved_models/changji/unet3d
  partial_restore: false
  save_path: C:/Users/Think/Desktop/DeepSatModels-main/models/saved_models/changji/unet3d
  save_steps: 8000
  train_metrics_steps: 2000
DATASETS:
  eval:
    base_dir: D:/2/data
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold5
    extra_data: null
    max_seq_len: 21
    num_workers: 0
    paths: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/csv/qita/val.csv
  test:
    base_dir: D:/2/data
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold5
    extra_data: null
    max_seq_len: 21
    num_workers: 0
    paths: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/csv/qita/test.csv
  train:
    base_dir: D:/2/data
    batch_size: 4
    bidir_input: false
    dataset: PASTIS24_fold5
    extra_data: null
    max_seq_len: 21
    num_workers: 0
    paths: C:/Users/Think/Desktop/bq/bq_new_new/kuochong_30/64/csv/qita/train.csv
MODEL:
  architecture: UNET3D
  dropout: 0.2
  img_res: 64
  max_seq_len: 21
  num_channels: 21
  num_classes: 4
  shape_pattern: NTHWC
SOLVER:
  class_weights: null
  loss_function: masked_cross_entropy
  lr_base: 0.0001
  lr_decay: 0.975
  lr_scheduler: constant
  num_epochs: 100
  reset_lr: true
  reset_lr_at_epoch: 150
local_device_ids:
- 0
