MODEL:
  architecture: "UNET3D"
  shape_pattern: 'NTHWC'
  img_res: 24
  max_seq_len: 60
  num_channels: 11
  num_classes: 19
  dropout: 0.2

DATASETS:
  train:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
  eval:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
  test:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
SOLVER:
  num_epochs: 100
  loss_function: masked_cross_entropy
  class_weights:
  lr_scheduler: 'constant'
  lr_base: 0.0001
  lr_decay: 0.975
  reset_lr: True   # resets lr to base value when loading pretrained model
  reset_lr_at_epoch: 150

CHECKPOINT:
  load_from_checkpoint:
  partial_restore: False
  save_path: "D:/save_pth/PASTIS/unet3d"

  log_path: 'D:/save_logs/PASTIS/unet3d'
  train_metrics_steps: 2000
  eval_steps: 4000
  save_steps: 8000