MODEL:
  architecture: "UNET3Df"
  train_stage: 2
  shape_pattern: "NTHWC"
  img_res: 24
  max_seq_len: 60
  emb_channels: 128
  num_channels: 11
  num_classes: 19
  dropout: 0.2

DATASETS:
  train:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
  eval:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
  test:
    dataset: 'PASTIS24_fold1'
    max_seq_len: 24
    batch_size: 4
    extra_data:
    num_workers: 0
SOLVER:
  num_epochs: 100
  num_warmup_epochs: 10
  loss_function: masked_cross_entropy
  class_weights:
  lr_scheduler: 'constant'
  num_cycles: 4
  lr_base: 0.0001
  lr_min: 5e-5
  lr_start: 1e-8
  lr_decay: 0.975
  reset_lr: True   # resets lr to base value when loading pretrained model
  reset_lr_at_epoch: 150

CHECKPOINT:
  load_from_checkpoint:
  partial_restore: False
  save_path: "models/saved_models/PASTIS/UNET3Df"

  log_path: 'models/saved_models/PASTIS/logs_UNET3Df'
  train_metrics_steps: 2000
  eval_steps: 4000
  save_steps: 8000
